name: database_adapter_postgre
version: 0.2.0
description: An adapter for using 'package:database' API with a PostgreSQL database.
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.6.0 <3.7.0'

dependencies:
  collection: ^1.14.0
  database: ^0.3.0
  meta: ^1.1.0
  postgres: ^2.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.8.0

dependency_overrides:
  database:
    path: '../../database'